/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package machinecafe;

/**
 *
 * @author lenovo
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }
    
    Machine m1 = new Machine("MPE");
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cafenoir = new javax.swing.JButton();
        cafelatte = new javax.swing.JButton();
        cafeitalien = new javax.swing.JButton();
        cafeserre = new javax.swing.JButton();
        cafearabica = new javax.swing.JButton();
        cafeexpresso = new javax.swing.JButton();
        reinitialisation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        prixtotal = new javax.swing.JLabel();
        pT = new javax.swing.JLabel();
        quantitétotal = new javax.swing.JLabel();
        qT = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quitter = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cafenoir.setBackground(new java.awt.Color(0, 0, 0));
        cafenoir.setFont(new java.awt.Font("d La Cruz", 0, 20)); // NOI18N
        cafenoir.setForeground(new java.awt.Color(255, 255, 255));
        cafenoir.setText("café noir");
        cafenoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafenoirActionPerformed(evt);
            }
        });

        cafelatte.setBackground(new java.awt.Color(0, 0, 0));
        cafelatte.setFont(new java.awt.Font("d La Cruz", 0, 20)); // NOI18N
        cafelatte.setForeground(new java.awt.Color(255, 255, 255));
        cafelatte.setText("Café Latte");
        cafelatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafelatteActionPerformed(evt);
            }
        });

        cafeitalien.setBackground(new java.awt.Color(0, 0, 0));
        cafeitalien.setFont(new java.awt.Font("d La Cruz", 0, 20)); // NOI18N
        cafeitalien.setForeground(new java.awt.Color(255, 255, 255));
        cafeitalien.setText("Café Italien ");
        cafeitalien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeitalienActionPerformed(evt);
            }
        });

        cafeserre.setBackground(new java.awt.Color(0, 0, 0));
        cafeserre.setFont(new java.awt.Font("d La Cruz", 0, 20)); // NOI18N
        cafeserre.setForeground(new java.awt.Color(255, 255, 255));
        cafeserre.setText("Café Serré");
        cafeserre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeserreActionPerformed(evt);
            }
        });

        cafearabica.setBackground(new java.awt.Color(0, 0, 0));
        cafearabica.setFont(new java.awt.Font("d La Cruz", 0, 20)); // NOI18N
        cafearabica.setForeground(new java.awt.Color(255, 255, 255));
        cafearabica.setText("Café Arabica");
        cafearabica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafearabicaActionPerformed(evt);
            }
        });

        cafeexpresso.setBackground(new java.awt.Color(0, 0, 0));
        cafeexpresso.setFont(new java.awt.Font("d La Cruz", 0, 20)); // NOI18N
        cafeexpresso.setForeground(new java.awt.Color(255, 255, 255));
        cafeexpresso.setText("Café Expresso");
        cafeexpresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeexpressoActionPerformed(evt);
            }
        });

        reinitialisation.setBackground(new java.awt.Color(153, 153, 153));
        reinitialisation.setFont(new java.awt.Font("Baar Sophia", 0, 16)); // NOI18N
        reinitialisation.setText("Réinitialiser");
        reinitialisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinitialisationActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("a Anti Corona", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText(" MACHINE A CAFE");

        jLabel2.setFont(new java.awt.Font("a Anti Corona", 0, 18)); // NOI18N
        jLabel2.setText("SELECTIONNER :");

        prixtotal.setFont(new java.awt.Font("Baar Sophia", 0, 20)); // NOI18N
        prixtotal.setText("Prix total:");

        pT.setFont(new java.awt.Font("Baar Sophia", 0, 20)); // NOI18N
        pT.setText("0 €");

        quantitétotal.setFont(new java.awt.Font("Baar Sophia", 0, 20)); // NOI18N
        quantitétotal.setText("Quantite total:");

        qT.setFont(new java.awt.Font("Baar Sophia", 0, 20)); // NOI18N
        qT.setText("0");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nouveau dossier/télécharger (1).png"))); // NOI18N

        quitter.setBackground(new java.awt.Color(153, 153, 153));
        quitter.setFont(new java.awt.Font("Baar Sophia", 0, 16)); // NOI18N
        quitter.setText("Quitter");
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Baar Sophia", 0, 14)); // NOI18N
        jLabel5.setText("1 €");

        jLabel6.setFont(new java.awt.Font("Baar Sophia", 0, 14)); // NOI18N
        jLabel6.setText("    2 €");

        jLabel7.setFont(new java.awt.Font("Baar Sophia", 0, 14)); // NOI18N
        jLabel7.setText("1.5 €");

        jLabel8.setFont(new java.awt.Font("Baar Sophia", 0, 14)); // NOI18N
        jLabel8.setText("1.2 €");

        jLabel9.setFont(new java.awt.Font("Baar Sophia", 0, 14)); // NOI18N
        jLabel9.setText("1.8 €");

        jLabel10.setFont(new java.awt.Font("Baar Sophia", 0, 14)); // NOI18N
        jLabel10.setText("  0.8 €");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cafenoir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cafeitalien, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cafearabica, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cafeserre, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cafelatte, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cafeexpresso, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prixtotal)
                            .addComponent(quantitétotal))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pT, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qT, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reinitialisation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cafenoir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cafearabica, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cafelatte, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cafeexpresso, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cafeitalien, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cafeserre, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(46, 46, 46)
                .addComponent(reinitialisation)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantitétotal)
                    .addComponent(qT))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prixtotal)
                            .addComponent(pT))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitter)
                        .addGap(25, 25, 25))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 720, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cafelatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafelatteActionPerformed
         Cafe latte = new Cafe("Latte", 1.5);
        m1.commande(latte);
        String q = String.valueOf(m1.getNbCafe());
        qT.setText(q);
        String p = String.valueOf(m1.getPrixTotalCafe());
        pT.setText(p + " €");
    }//GEN-LAST:event_cafelatteActionPerformed

    private void cafeitalienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeitalienActionPerformed
        Cafe italien = new Cafe("Italien", 1.8);
        m1.commande(italien);
        String q = String.valueOf(m1.getNbCafe());
        qT.setText(q);
        String p = String.valueOf(m1.getPrixTotalCafe());
        pT.setText(p + " €");
    }//GEN-LAST:event_cafeitalienActionPerformed

    private void cafeexpressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeexpressoActionPerformed
        Cafe expresso = new Cafe("Noir", 1.2);
        m1.commande(expresso);
        String q = String.valueOf(m1.getNbCafe());
        qT.setText(q);
        String p = String.valueOf(m1.getPrixTotalCafe());
        pT.setText(p + " €");
    }//GEN-LAST:event_cafeexpressoActionPerformed

    private void cafeserreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeserreActionPerformed
        Cafe serre = new Cafe("Serré", 0.8);
        m1.commande(serre);
        String q = String.valueOf(m1.getNbCafe());
        qT.setText(q);
        String p = String.valueOf(m1.getPrixTotalCafe());
        pT.setText(p + " €");
    }//GEN-LAST:event_cafeserreActionPerformed

    private void reinitialisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinitialisationActionPerformed
        m1.reintialiser();
        qT.setText("0");
        pT.setText("0 €");
    }//GEN-LAST:event_reinitialisationActionPerformed

    private void cafearabicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafearabicaActionPerformed
        Cafe arabica = new Cafe("Arabica", 2);
        m1.commande(arabica);
        String q = String.valueOf(m1.getNbCafe());
        qT.setText(q);
        String p = String.valueOf(m1.getPrixTotalCafe());
        pT.setText(p + " €");
    }//GEN-LAST:event_cafearabicaActionPerformed

    private void cafenoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafenoirActionPerformed
        Cafe noir = new Cafe("Noir", 1);
        m1.commande(noir);
        String q = String.valueOf(m1.getNbCafe());
        qT.setText(q);
        String p = String.valueOf(m1.getPrixTotalCafe());
        pT.setText(p + " €");

    }//GEN-LAST:event_cafenoirActionPerformed

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
        this.dispose();
    }//GEN-LAST:event_quitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cafearabica;
    private javax.swing.JButton cafeexpresso;
    private javax.swing.JButton cafeitalien;
    private javax.swing.JButton cafelatte;
    private javax.swing.JButton cafenoir;
    private javax.swing.JButton cafeserre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel pT;
    private javax.swing.JLabel prixtotal;
    private javax.swing.JLabel qT;
    private javax.swing.JLabel quantitétotal;
    private javax.swing.JButton quitter;
    private javax.swing.JButton reinitialisation;
    // End of variables declaration//GEN-END:variables
}
